In [1]:
import numpy as np

In [2]:
a = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])
b = np.array([1,2,3])

In [3]:
a * b

array([[0.1, 0.4, 0.9],
       [0.4, 1. , 1.8],
       [0.7, 1.6, 2.7]])

In [4]:
1.0 - a

array([[0.9, 0.8, 0.7],
       [0.6, 0.5, 0.4],
       [0.3, 0.2, 0.1]])

In [5]:
a * b - (1.0 - a)

array([[-0.8, -0.4,  0.2],
       [-0.2,  0.5,  1.4],
       [ 0.4,  1.4,  2.6]])

In [6]:
np.max(a * b - (1.0 - a), axis=1)

array([0.2, 1.4, 2.6])

In [7]:
a - a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
from scipy.sparse import dok_matrix

In [35]:
c = dok_matrix((3,3))
d = dok_matrix((1,3))
e = dok_matrix((3,3))
c[0, 0] = 0.1
c[0, 1] = 0.2
c[0, 2] = 0.3
c[1, 0] = 0.4
c[1, 1] = 0.5
c[1, 2] = 0.6
c[2, 0] = 0.7
c[2, 1] = 0.8
c[2, 2] = 0.9


d[0, 0] = 1
d[0, 1] = 2
d[0, 2] = 3

e[0, 0] = 0.1
e[0, 1] = 0.2
e[0, 2] = 0.3
e[1, 0] = 0.4
e[1, 1] = 0.5
e[1, 2] = 0.6
e[2, 0] = 0.7
e[2, 1] = 0.8
e[2, 2] = 0.9

In [34]:
(c.multiply(d)).toarray()

array([[0.1, 0.4, 0.9],
       [0.4, 1. , 1.8],
       [0.7, 1.6, 2.7]])

In [40]:
(-1 * e).toarray()

array([[-0.1, -0.2, -0.3],
       [-0.4, -0.5, -0.6],
       [-0.7, -0.8, -0.9]])

In [41]:
e.copy()

<3x3 sparse matrix of type '<type 'numpy.float64'>'
	with 9 stored elements in Dictionary Of Keys format>

In [42]:
import torch

ImportError: No module named torch