In [1]:
from trajectory_generation import TrajectoryGenerator
from trimesh_util import create_axis_arrow, create_axis_arrows, sample_points_on_mesh
import sys
import rospy
import moveit_commander
import random
from moveit_msgs.srv import GetStateValidity, GetStateValidityRequest
from moveit_msgs.msg import RobotState
from sensor_msgs.msg import JointState

import numpy as np
import pickle
from os import path as osp
import os
import shutil
import trimesh

In [2]:
rospy.init_node('data_trajectory_generation')
moveit_commander.roscpp_initialize(sys.argv)
trajectory_generator = TrajectoryGenerator(moveit_commander)

In [3]:
meshlist = trajectory_generator.generate_random_mesh(5)
pointcloud = trajectory_generator.setObstaclesInScene(meshlist)
trajectory_generator.show_point_cloud(pointcloud)

In [4]:
print len(pointcloud)

307200


In [5]:
print pointcloud[:10]

[[ 10.          -3.01757087   5.05288808]
 [  0.1         -0.03017571   1.04052888]
 [  0.1         -0.03017571   1.04052888]
 [  0.1         -0.03017571   1.04052888]
 [  0.1         -0.03017571   1.04052888]
 [  0.1         -0.03017571   1.04052888]
 [  0.1         -0.03017571   1.04052888]
 [  0.1         -0.03017571   1.04052888]
 [  0.1         -0.03017571   1.04052888]
 [  0.1         -0.03017571   1.04052888]]


In [ ]:
result, sampledTrajectory = trajectory_generator.generateValidTrajectory()

In [ ]:
trajectory_generator.cleanPlanningScene()